# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/images')),
            ],
            options={
                'verbose_name': 'Journal Image',
                'verbose_name_plural': 'Journal Images',
            },
        ),
        migrations.RemoveField(
            model_name='journal',
            name='image',
        ),
        migrations.AddField(
            model_name='journalimage',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal'),
        ),
    ]
