# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20170717_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalYoutube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
            ],
            options={
                'verbose_name': 'Journal Youtube Url',
                'verbose_name_plural': 'Journal Youtube Urls',
            },
        ),
    ]
