# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20170718_1640'),
        ('journal', '0004_auto_20170911_1824'),
    ]

    operations = [
    ]
