WEIGHT_PRODUCT = 2.5		### in KG


FREE_SHIPPING_INDIA_AMOUNT = 0		### in INR
FREE_SHIPPING_OTHERS_AMOUNT = 100000		### in INR


ZONE_PRICING = {
	'A': 3874,
	'B': 4421,
	'C': 4174,
	'D': 4421,
	'E': 4978,
	'F': 2870,
	'G': 2713,
	'H': 6506,
	'I': 7707,
	'J': 3914,
	'K': 4903,
	'L': 2372,
	'M': 2738,
}


ZONES = {
	'India': 'B',
	'Afghanistan': 'K',
	'Albania': 'K',
	'Algeria': 'K',
	'American Samoa': 'I',
	'Andorra': 'H',
	'Angola': 'K',
	'Anguilla': 'J',
	'Antigua': 'J',
	'Argentina': 'J',
	'Armenia': 'K',
	'Aruba': 'J',
	'Australia': 'F',
	'Austria': 'G',
	'Azerbaijan': 'K',
	'Bahamas': 'J',
	'Bahrain': 'D',
	'Bangladesh': 'A',
	'Barbados': 'J',
	'Belarus': 'H',
	'Belgium': 'G',
	'Belize': 'J',
	'Benin': 'K',
	'Bermuda': 'J',
	'Bhutan': 'A',
	'Bolivia': 'J',
	'Bonaire': 'J',
	'Bosnia & Herzegovina': 'K',
	'Botswana': 'K',
	'Brazil': 'J',
	'Brunei': 'E',
	'Bulgaria': 'H',
	'Burkina Faso': 'K',
	'Burundi': 'K',
	'Cambodia': 'E',
	'Cameroon': 'K',
	'Canada': 'M',
	'Canary Islands': 'H',
	'Cape Verde': 'K',
	'Cayman Islands': 'J',
	'Central African': 'K',
	'Chad': 'K',
	'Chile': 'J',
	'China': 'C',
	'Colombia': 'J',
	'Comoros': 'K',
	'Congo': 'K',
	'Congo': 'K',
	'Cook Islands': 'K',
	'Costa Rica': 'J',
	"Cote d'Ivoire": 'K',
	'Croatia': 'K',
	'Cuba': 'J',
	'Curacao': 'J',
	'Cyprus': 'H',
	'Czech Republic': 'G',
	'Denmark': 'G',
	'Djibouti': 'K',
	'Dominica': 'J',
	'Dominican': 'J',
	'East Timor': 'E',
	'Ecuador': 'J',
	'Egypt': 'K',
	'El Salvador': 'J',
	'Eritrea': 'K',
	'Estonia': 'H',
	'Ethiopia': 'K',
	'Falkland Islands': 'H',
	'Faroe Islands': 'H',
	'Fiji': 'K',
	'Finland': 'H',
	'France': 'G',
	'French Guyana': 'J',
	'Gabon': 'K',
	'Gambia': 'K',
	'Georgia': 'K',
	'Germany': 'G',
	'Ghana': 'K',
	'Gibraltar': 'H',
	'Greece': 'H',
	'Greenland': 'H',
	'Grenada': 'J',
	'Guadeloupe': 'J',
	'Guam': 'I',
	'Guatemala': 'J',
	'Guernsey': 'H',
	'Guinea Republic': 'K',
	'Guinea-Bissau': 'K',
	'Guinea-Equatorial': 'K',
	'Guyana (British)': 'J',
	'Haiti': 'J',
	'Honduras': 'J',
	'Hong Kong': 'B',
	'Hungary': 'G',
	'Iceland': 'H',
	'Indonesia': 'E',
	'Iran': 'D',
	'Iraq': 'K',
	'Ireland': 'G',
	'Israel': 'H',
	'Italy': 'G',
	'Jamaica': 'J',
	'Japan': 'E',
	'Jersey': 'H',
	'Jordan': 'D',
	'Kazakhstan': 'K',
	'Kenya': 'K',
	'Kiribati': 'K',
	'Korea': 'E',
	'Kosovo': 'K',
	'Kuwait': 'D',
	'Kyrgyzstan': 'K',
	'Lao PDR': 'E',
	'Latvia': 'H',
	'Lebanon': 'D',
	'Lesotho': 'K',
	'Liberia': 'K',
	'Libya': 'K',
	'Liechtenstein': 'G',
	'Lithuania': 'H',
	'Luxembourg': 'G',
	'Macau': 'E',
	'Macedonia': 'K',
	'Madagascar': 'K',
	'Malawi': 'K',
	'Malaysia': 'B',
	'Maldives': 'A',
	'Mali': 'K',
	'Malta': 'H',
	'Marshall Islands': 'I',
	'Martinique': 'J',
	'Mauritania': 'K',
	'Mauritius': 'K',
	'Mayotte': 'K',
	'Mexico': 'I',
	'Micronesia': 'K',
	'Moldova': 'K',
	'Monaco': 'G',
	'Mongolia': 'E',
	'Montenegro': 'K',
	'Montserrat': 'J',
	'Morocco': 'K',
	'Mozambique': 'K',
	'Myanmar': 'E',
	'Namibia': 'K',
	'Nauru': 'K',
	'Nepal': 'A',
	'Netherlands Antilles': 'H',
	'Netherlands, The': 'G',
	'Nevis': 'J',
	'New Caledonia': 'K',
	'New Zealand': 'F',
	'Nicaragua': 'J',
	'Niger': 'K',
	'Nigeria': 'K',
	'Niue': 'K',
	'Norway': 'H',
	'Oman': 'D',
	'Pakistan': 'D',
	'Palau': 'K',
	'Panama': 'J',
	'Papua New Guinea': 'F',
	'Paraguay': 'J',
	'Peru': 'J',
	'Philippines, The': 'E',
	'Poland': 'G',
	'Portugal': 'G',
	'Puerto Rico': 'I',
	'Qatar': 'D',
	'Reunion Island': 'K',
	'Romania': 'G',
	'Russia': 'H',
	'Rwanda': 'K',
	'Saipan': 'I',
	'Samoa': 'K',
	'San Marino': 'K',
	'Sao Tome': 'K',
	'Saudi Arabia': 'D',
	'Senegal': 'K',
	'Serbia': 'K',
	'Seychelles': 'K',
	'Sierra Leone': 'K',
	'Singapore': 'B',
	'Slovakia': 'G',
	'Slovenia': 'H',
	'Solomon Islands': 'K',
	'Somalia': 'K',
	'Somaliland': 'K',
	'South Africa': 'J',
	'Spain': 'G',
	'Sri Lanka': 'A',
	'St. Barthelemy': 'J',
	'St. Eustatius': 'J',
	'St. Kitts': 'J',
	'St. Lucia': 'J',
	'St. Vincent': 'J',
	'Sudan': 'K',
	'Suriname': 'J',
	'Swaziland': 'K',
	'Sweden': 'G',
	'Switzerland': 'G',
	'Syria': 'D',
	'Tahiti': 'K',
	'Taiwan': 'E',
	'Tajikistan': 'K',
	'Tanzania': 'K',
	'Thailand': 'B',
	'Togo': 'K',
	'Tonga': 'K',
	'Trinidad and Tobago': 'J',
	'Tunisia': 'K',
	'Turkey': 'H',
	'Turkmenistan': 'K',
	'Turks and Caicos': 'J',
	'Tuvalu': 'K',
	'Uganda': 'K',
	'Ukraine': 'K',
	'United Arab Emirates': 'A',
	'United Kingdom': 'G',
	'USA': 'L',
	'Uruguay': 'J',
	'Uzbekistan': 'K',
	'Vanuatu': 'K',
	'Venezuela': 'J',
	'Vietnam': 'E',
	'Virgin Islands (British)': 'J',
	'Virgin Islands (US)': 'I',
	'Yemen, Republic of': 'D',
	'Zambia': 'K',
	'Zimbabwe': 'K',
}