# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import oscar.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('link_url', oscar.models.fields.ExtendedURLField(blank=True, help_text='This is where this promotion links to', verbose_name='Link URL')),
                ('image', models.ImageField(max_length=255, upload_to=b'images/promotions/', verbose_name='Image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='Text')),
                ('text_colour', models.CharField(default='', max_length=200, verbose_name='Text Colour')),
                ('button', models.CharField(default='', max_length=200, verbose_name='Button Text')),
            ],
        ),
    ]
