# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_block', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='link_url',
        ),
        migrations.AlterField(
            model_name='customimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='/media/promotions/custom-image', verbose_name='Image'),
        ),
    ]
