# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_block', '0003_auto_20170713_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='link_url',
            field=models.URLField(blank=True, help_text='This is where this promotion links to', verbose_name='Link URL'),
        ),
    ]
