# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_block', '0006_auto_20170911_1824'),
        ('custom_block', '0006_auto_20170714_1625'),
    ]

    operations = [
    ]
